package replay_test

import (
	"context"
	"os"
	"reflect"
	"testing"

	"github.com/Dealwatch/Tabularium117/internal/model"
	"github.com/Dealwatch/Tabularium117/internal/protocol"
	"github.com/Dealwatch/Tabularium117/internal/replay"
)

// fixturePath is the recording generated by tools/reencode-connector from the
// connector's decoded capture. It is re-encoded, not captured from the game
// (see testdata/README.md); the numbers asserted here are the ones
// docs/protocol.md reports for that capture.
const fixturePath = "../../testdata/connector-reencoded.jsonl"

func TestConnectorFixtureDecodes(t *testing.T) {
	f, err := os.Open(fixturePath)
	if err != nil {
		t.Fatalf("open fixture: %v", err)
	}
	defer f.Close()

	frames, err := collect(context.Background(), replay.NewReader(f, replay.Options{Speed: 0}))
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if len(frames) != 16 {
		t.Fatalf("fixture has %d frames, want 16", len(frames))
	}

	var (
		snapshots []model.IslandSnapshot
		products  int
		sawStart  bool
	)
	for i, frame := range frames {
		msg, err := protocol.Decode(frame.Payload, frame.ReceivedAt)
		if err != nil {
			t.Fatalf("decode frame %d: %v", i, err)
		}
		switch m := msg.(type) {
		case protocol.Version:
			if i != 0 {
				t.Errorf("Version frame at index %d, want 0", i)
			}
			if err := protocol.CheckVersion(m); err != nil {
				t.Errorf("CheckVersion: %v", err)
			}
		case protocol.SessionStart:
			sawStart = true
		case protocol.AreaStatistics:
			if !m.Snapshot.ReceivedAt.Equal(frame.ReceivedAt) {
				t.Errorf("frame %d: ReceivedAt = %v, want the recorded %v", i, m.Snapshot.ReceivedAt, frame.ReceivedAt)
			}
			snapshots = append(snapshots, m.Snapshot)
			products += len(m.Snapshot.Products)
		default:
			t.Errorf("frame %d: unexpected message %T", i, msg)
		}
	}

	if !sawStart {
		t.Error("no SessionStart frame in the fixture")
	}
	if len(snapshots) != 14 {
		t.Errorf("got %d island snapshots, want 14", len(snapshots))
	}
	if products != 423 {
		t.Errorf("got %d product entries in total, want 423", products)
	}

	// The identity gotcha: island ID 5 exists in both sessions and is a
	// different island each time.
	byKey := make(map[model.IslandKey]model.IslandSnapshot, len(snapshots))
	for _, s := range snapshots {
		if _, dup := byKey[s.Key]; dup {
			t.Errorf("duplicate island key %+v", s.Key)
		}
		byKey[s.Key] = s
	}
	for _, guid := range []int32{3245, 6627} {
		key := model.IslandKey{SessionGUID: guid, IslandID: 5}
		if _, ok := byKey[key]; !ok {
			t.Errorf("no island %+v in the fixture", key)
		}
	}
	if a, b := byKey[model.IslandKey{SessionGUID: 3245, IslandID: 5}], byKey[model.IslandKey{SessionGUID: 6627, IslandID: 5}]; a.Name == b.Name {
		t.Errorf("both islands with ID 5 are named %q; the key must separate them", a.Name)
	}

	// One entry checked against the connector's JSON, so that a field mapped to
	// the wrong slot in the tool or the decoder does not hide behind the counts.
	juliana := byKey[model.IslandKey{SessionGUID: 3245, IslandID: 5}]
	if juliana.Name != "Juliana" || juliana.SessionID != 1 || juliana.AreaIndex != 1 || juliana.GameTimestamp != 374522200 {
		t.Errorf("island 3245/5 header = %+v", model.IslandSnapshot{
			Key: juliana.Key, SessionID: juliana.SessionID, AreaIndex: juliana.AreaIndex,
			Name: juliana.Name, GameTimestamp: juliana.GameTimestamp,
		})
	}
	if len(juliana.Products) != 56 {
		t.Fatalf("island %q has %d products, want 56", juliana.Name, len(juliana.Products))
	}
	want := model.ProductStat{
		ProductGUID:        2068,
		Generation:         float32(23.191875457763672),
		Consumption:        float32(24.699996948242188),
		Delta:              float32(-1.5081214904785156),
		PerfectGeneration:  float32(27.9168758392334),
		PerfectConsumption: float32(24.699996948242188),
		Buildings:          6,
		Maintenance:        24,
		Income:             0,
		Profit:             -24,
		SummedProductivity: float32(27.873546600341797),
		AvgProductivity:    float32(464.5591125488281),
		Workforce:          map[int32]int32{2181: 18},
		BuildingsByGUID:    map[int32]int32{2200: 6},
	}
	if got := juliana.Products[0]; !reflect.DeepEqual(got, want) {
		t.Errorf("island %q first product\n got: %+v\nwant: %+v", juliana.Name, got, want)
	}

	// A name is stored exactly as delivered, trailing space included, and an
	// island can have no products at all.
	var empty []model.IslandSnapshot
	for _, s := range snapshots {
		if s.Name == "Zycada " {
			empty = append(empty, s)
		}
	}
	if len(empty) != 1 {
		t.Fatalf("got %d islands named %q, want 1", len(empty), "Zycada ")
	}
	if len(empty[0].Products) != 0 {
		t.Errorf("island %q has %d products, want 0", empty[0].Name, len(empty[0].Products))
	}
}
