// Package catalog maps game GUIDs to names, categories, and regions.
//
// The data in catalog.json is generated by tools/gen-catalog from a pinned
// revision of anno-mods/anno-117-calculator (see THIRD_PARTY_NOTICES.md);
// unknown GUIDs fall back to "#GUID" and are logged once.
package catalog
